apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: ruresh/rsuresh_openmrs:1.0
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: ruresh/rsuresh_openmrs:1.0  
  template:
    metadata:
      labels:
        app: ruresh/rsuresh_openmrs:1.0
    spec:
      hostNetwork: true
      containers:
      - image: ruresh/rsuresh_openmrs:1.0
        name: opnmrs
        ports:
        - containerPort: 8080