apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: openmrs
spec:
  replicas: 1
  #strategy:
  #  type: RollingUpdate
  #  rollingUpdate:
  #   maxSurge: 1
  #    maxUnavailable: 1
  selector:
    matchLabels:
      app:  openmrs 
  template:
    metadata:
      labels:
        app: openmrs
    spec:
      hostNetwork: true
      containers:
      - image: rsuresh/rsuresh_openmrs:1.0
        name: openmrs
        ports:
        - containerPort: 8080